# Sphinx is pinned to 6.2.1, can be any really, but not 7.2.5 as this bug with Numpy
# arose: https://github.com/numpy/numpy/issues/24604
name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install sphinx==6.2.1 sphinx_rtd_theme recommonmark myst_parser
      - name: Sphinx build
        run: |
          sphinx-build docsource docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
